# https://rdrn.me/postmodern-python/
[project]
name = "import-users"
version = "0.1.0"
description = "Import users and groups to AWS IAM from CSV."
readme = "README.md"
requires-python = ">=3.13"
# You can add an editable dependency with `uv add --editable $path_to_package`
dependencies = [
    "boto3[crt]>=1.38.24",
    "email-validator>=2.2.0",
    "pydantic>=2.11.5",
]

[dependency-groups]
dev = [
    "boto3-stubs[iam]>=1.38.31", # type hints for boto3 iam
    "coverage[toml]>=7.8.2", # measure code coverage
    "icecream>=2.1.4", # for printf debugging
    "moto[iam]>=5.1.5", # for mocking AWS services in tests
    "poethepoet>=0.34.0", # used to run project specific scripts/tasks
    "pyright>=1.1.401", # for static type checking
    "pytest>=8.3.5", # for writing automated tests
    "pytest-cov>=6.1.1", # integrate coverage with pytest
    "ruff>=0.11.11", # for formatting and linting
]

# necessary for project.scripts to work.
[tool.uv]
package = true

[tool.pyright]
venvPath = "." # uv installs the venv in the current dir
venv = ".venv" # in a folder called `.venv`
strict = ["**/*.py"] # use 'strict' checking on all files
pythonVersion = "3.13" # if library, specify the _lowest_ you support

[tool.ruff]
# if this is a library, enter the _minimum_ version you
# want to support, otherwise do py313
target-version = "py313"
line-length = 120  # use whatever number makes you happy

[tool.ruff.lint]
# you can see the looong list of rules here:
# https://docs.astral.sh/ruff/rules/
# here's a couple to start with
select = [
	"A",    # warn about shadowing built-ins
	"E",    # style stuff, whitespaces
	"F",    # important pyflakes lints
	"I",    # import sorting
	"N",    # naming
	"T100", # breakpoints (probably don't want these in prod!)
]
# if you're feeling confident you can do:
# select = ["ALL"]
# and then manually ignore annoying ones:
# ignore = [...]

[tool.ruff.lint.isort]
# so it knows to group first-party stuff last
known-first-party = ["postmodern"]

[tool.pytest.ini_options]
addopts = "--doctest-modules" # test docstrings in modules
# Ignore error cause by botocore https://github.com/boto/boto3/issues/3889
filterwarnings = [
    "ignore:datetime.datetime.utcnow:DeprecationWarning:botocore"
]

[tool.coverage.run]
source = ["import_users"]
branch = true

[tool.coverage.report]
fail_under = 90
show_missing = true

[project.scripts]
# This is the entry point for the program, you can run it with `uv run import-users`
# https://docs.astral.sh/uv/concepts/projects/config/#entry-points
import-users = "import_users.__main__:main"

# You can define a GUI for the project in this section.
# [project.gui-scripts]
# import-users-gui = "import_users.__main__:main_gui"

[tool.poe.tasks]
# run with eg `uv run poe fmt`
fmt = "ruff format"
lint = "ruff check --fix"
check = "pyright"
test = "pytest"
cov = "coverage report -m"
# run all the above with `uv run poe all`
all = [ {ref="fmt"}, {ref="lint"}, {ref="check"}, {ref="test"}, {ref="cov"}]
